### PR TITLE
refactor to use hyper's tokio branch

### PR DESCRIPTION
**Pull request by alsuren**
This is completely untested, and may not even be a good idea (chatbots are
unlikely to be performance-critical, given FB's rate limits) but I wanted
an excuse to play about with futures, and this gave me the opportunity.

I don't genuinely expect you to merge this, but I thought I should at least
make you aware of my work in case you had any comments.

My editor stomps on everything by default, and I had already made significant
progress before I realised that the diff was full of style changes. I decided
that the most sensible thing to do would be to pass the whole thing through
rustfmt first, and then rebase my functionality changes on top of the style
changes.

I will probably be writing some webhook handling code over the next week or so.
If you happen to have any HMAC verifying code kicking around (I assume you do because none of the functions in this repo can be used without working webhooks), I would appreciate being able to have a look at it. Otherwise, I will probably just port my python implementation across to rust.

### CODE REVIEW

**Comment by nocotan** [comment]
Thank you so much! This is very helpful!
After testing, I will merge.

**Comment by alsuren** [comment]
Actually you might want to wait until hyper make an official release using
tokio.

I'm currently having trouble implementing a hyper::Service which is able to
react to webhooks by replying with an echo.

The example I provided works fine, but if I create the core and http client
in the thread/task that's doing the http request  (see a previous commit on
this branch) then I get a spurious "No route to host" error out of the
future. If I try to pass the core into the Service from outside then the
compiler shouts at me for trying to Send it across a thread boundary.

It might be a fundamental problem with the apI of Service or I might be
missing something.

When I have a working echo bot then I will try to refactor this branch and
provide an example. Until then, probably best to wait.

**Comment by alsuren** [comment]
Turns out the problem was on the server side: hyper::server::Http::bind(|| -> Service) should probably be hyper::server::Http::bind(|Handle| -> Service). I'm currently running my echo bot on https://rust-messenger.herokuapp.com/webhook (I've not currently got any HMAC verification so you can POST all sorts of rubbish if you're in the mood).

https://github.com/alsuren/heroku-rust-cargo-hello/ contains the code for the bot (it's a bit of a rat's nest, but I'm hoping to refactor as much as I can into rmessenger as I make progress).

I'm going to force-push to rewrite the history a bit.

**Comment by alsuren** [comment]
Force-pushed. I would like to squash `refactor to use hyper's tokio branch  …` and `pass a hyper::Client into Bot  …` into a single commit, but I can't be bothered to fix the merge conflicts that this causes with the commits in between. Feel free to merge as-is.

**Comment by nocotan** [comment]
ac

**Pull request merged**
